tracker: ../lib/csapp.c ../lib/csapp.h recv_mem.c recv_mem.h sort_mem.c sort_mem.h to_client.c to_client.h tracker.c
	gcc tracker.c ../lib/csapp.c ../lib/csapp.h recv_mem.c recv_mem.h sort_mem.c sort_mem.h to_client.c to_client.h -o tracker -lpthread
clean:
	-rm -rf *.o tracker
